name: Test

on:
  push:
  pull_request:

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
      - name: Run RSpec
        run: |
        gem install rspec
        rspec