name: Test

on:
  push:
  pull_request:

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
          bundler-cache: true
          working-directory: backen
      - name: Run RSpec
        run: bundle exec rspec