name: Run rspec

on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Test with Rspec
        run: |
          gem install bundler
          bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
          bundle exec rspec
